"handler":
  "request_body_limit": 1048576

"postgres_config":
  "url": "localhost:5432"
  "max_connections": 10
  "database": "postgres"

"postgres_repo_config":
  "schema": "public"

"redis_config":
  "port": 6379
  "host": "localhost"